### ISSUE TITLE
How about to use threadpool to deliver big number of messages?

### ISSUE THREAD

**Issue by stereobooster** [holli/action_smser#14]
Something like this

```ruby
pool = Concurrent::FixedThreadPool.new(10, max_queue: 10_000)
formatted_numbers.each do |to|
  pool.post do
    deliver_path = self.deliver_path(sms, to, options)
    response = self.deliver_http_request(sms, options, deliver_path)
  end
 end
 pool.shutdown
 pool.wait_for_termination
```

Obviously this is not working example. But would you accept PR for this?

**Comment by holli** [comment]
I personally send everything through DelayedJob and have many workers so even a bigger number of messages are sent easily. But yes I can see the need for that in some cases.

I think that kind of feature could be easily added as a separate DeliveryMethod class and it wouldn't really change the architecture in any way? 

So you could look the example from delayed_job delivery method and create a custom class. Test if it works in your use cases and make a PR if it's good.
